<html>
<head>
    <meta charset="UTF-8">
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="../../Js/scripts.js"></script>
</head>
<body>
<form method="post" action="/?route=edit/add" onsubmit="return confirm('Do you really want to add it?')">
    New value in <b><?=$_POST['table']?></b>. Enter parameters: <br><br>
    <input name="table" value="<?=$_POST['table']?>" hidden>
    <?php
    foreach ($field as $key => $value){
        if ($key != 0) {
            echo $value;
        ?>
        <input name="<?=$value?>"><br>
        <?php
        }
    }
    ?>
    <button type="button" onclick="history.back()">Back</button>
    <button class="isValid">+add</button>
</form>
</body>
</html>
