
<form method="post" action="/?route=edit/update" onsubmit="return confirm('Do you really want to add it?')">
    Edit value in <b><?=$_POST['table']?></b>. Change parameters: <br><br>
    <input name="table" value="<?=$_POST['table']?>" hidden>
    <?php
    foreach ($info as $key => $value){
    if ( strripos($key, '_id')){
        ?><input name="<?=$key?>" value="<?=$value?>" hidden>
    <?php } else {
        echo $key.': ';?>
        <input name="<?=$key?>" value="<?=$value?>">
     <br>
        <?php    }}    ?>
    <br>
    <button type="button" onclick="history.back()">Back</button>
    <button class="isValid">Save changes</button>
</form>