
<form method="post" action="/?route=admin/selectSession">
    Select the Session: <select id="form_session" name="session_id">
        <?php
        foreach ($session_list['result'] as $i){
            ?><option><?=($i['session_id'])?></option>
        <?php     }      ?>
    </select>

    <button>Choose</button>
    or

    <a href="?route=admin/newSessionForm">Create new Session</a>



</form>
