<html>
<head>
    <meta charset="UTF-8">
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="../../Js/scripts.js"></script>
</head>
<body>
<form method="post" action="/?route=admin/selectSession">
    <div class="container">
        <div class="form-group">
            <div class="col-sm-10">
                <?php if (!$session_list['result'] == array()){?>
                    <label for="form_session" class="col-sm-3 control-label">Select the Session: </label>
                    <div class="col-sm-4">
                        <select class="form-control" id="form_session" name="session_id">
                            <?php
                            foreach ($session_list['result'] as $i){
                                ?><option value="<?=($i['session_id'])?>"><?=($i['date']).' - '.$i['session_name']?></option>
                            <?php     }      ?>
                        </select>
                    </div>
                    <div class="col-sm-1">
                        <button class="btn btn-default">Choose</button>
                    </div>
                <?php } else { ?>
                    <div class="col-sm-3">
                        <b>There are no sessions yet...</b>
                    </div>
                <?php }?>
                <div class="col-sm-2">
                    <a href="?route=admin/newSessionForm"><button type="button" class="btn btn-primary">Create new session</button></a>
                </div>
                <div class="col-sm-2">
                    <a href="?route=edit/index"><button type="button" class="btn btn-info">EDIT BASE</button></a>
                </div>
            </div>
        </div>
    </div>
</form>
</body>
</html>