<html>


<head>
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="../../Js/scripts.js"></script>
</head>
<body>
<div>
    <b>Session info</b><br>
    <i>
        <?php
        foreach ($session_info['result'] as $key => $param){
            echo $key.': '.$param.'<br>';
        }
        ?>
    </i>
    <hr>
</div>
<div>
    <b>Serie info</b><br>
    <i>
        <?php
        foreach ($serie_info['result'] as $key => $param){
            echo $key.': '.$param.'<br>';
        }
        ?>
    </i>
    <hr>
</div>

<form method="post" action="/?route=admin/addNewHit">
    <div id=divf>
        <b>hit 1:</b><br>
        <input type="text" name="serie_id" value="<?=$serie_info["result"]["serie_id"]?>" hidden>
        X: <input type=number name="hit_1[x]"><br>
        Y: <input type=number name="hit_1[y]">
    </div>

    <input id="add" type=button onclick=plus(); value="Add">
    <input id="delete" type=button onclick=minus(); value="delete">
    <hr>
    <button type="button" onclick="history.back()">Back</button>
    <button id="new_hits_btn">Save and add enother serie!</button>
    <br><br><br><a href="?route=admin/index"><button type="button">Finished session!</button></a>
</form>
</body>


</html>
