
<html>


<head>
    <meta charset="UTF-8">
   <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
   <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
   <script src="../../Js/scripts.js"></script>
</head>
<body>
    <div>
        <b>Session info</b><br>
        <i>
            <?php
            foreach ($session_info['result'] as $key => $param){
                echo $key.': '.$param.'<br>';
            }
            ?>
        </i>
        <hr>
    </div>


    <form method="post" action="/?route=admin/addNewSerie">
        <input type="text" name="session_id" value="<?=$session_info['result']['session_id']?>" hidden>
        <h4>Enter information about seria:</h4>

        <label for="form_seria_num">Serie Number: </label>
        <input id="form_seria_num" type="text" name="serie_number" value="<?=$for_new_serie['number']?>" readonly><br>

        <label for="form_color">Color: </label>
        <select id="form_color" name="color">
            <?php
            foreach ($for_new_serie['color_info'] as $i){
                ?><option><?=($i['color_name'])?></option>
            <?php    }     ?>
        </select><br>

        <label for="form_range">Range: </label>
        <input id="form_range" type="number" name="range"><br>

        <label for="form_scope">Scope: </label>
        <select id="form_scope" name="scope">
            <?php
            foreach ($for_new_serie['scope_info'] as $i){
                ?><option><?=($i['scope_name'])?></option>
            <?php    }     ?>
        </select><br>

        <label for="form_fireslyle">Firestyle: </label>
        <select id="form_fireslyle" name="firestyle">
            <?php
            foreach ($for_new_serie['firestyle_info'] as $i){
                ?><option><?=($i['firestyle_name'])?></option>
            <?php    }     ?>
        </select><br>

        <label for="form_serie_name">Serie name: </label>
        <input id="form_serie_name" type="text" name="serie_name"><br>

        <label for="form_serie_comment">Comments: </label>
        <textarea id="form_serie_comment" name="serie_comment"></textarea><br>


        <button type="button" onclick="history.back()">Back</button>
        <button id="new_serie_btn">Create new serie!</button>
        <br><br><br><a href="?route=admin/index"><button type="button">Finished session!</button></a>
    </form>
</body>


</html>


