
<form method="post" action="">

    <?php foreach ($hit_info['result'] as $key => $value){
        echo $key.': '?><input type="text" name="<?=$key?>" value="<?=$value?>" readonly><br>
    <?php }    ?>

    <button type="button" onclick="history.back()">Back</button>

</form>
<br>

<form method="post" action="/?route=admin/deleteHit" onsubmit="return confirm('Are you sure?')">
    <input name="hit_id" value="<?=$hit_info['result']['hit_id']?>" hidden>
    <button>Delete hit</button>
</form>

