<html>
<head>
    <meta charset="UTF-8">
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="../../Js/scripts.js"></script>
</head>
<body>


<table>
    <td>
        <tr>
            <form method="post" action="/?route=admin/editSerieForm">
                <?php foreach ($serie_info['result'] as $key => $value){
                    ?><input type="text" name="<?=$key?>" value="<?=$value?>" hidden>
                <?php }    ?>
                <button>Edit serie</button>
            </form>
        </tr>
        <tr>
            &nbsp &nbsp
        </tr>
        <tr>
            <form method="post" action="/?route=admin/deleteSerie" onsubmit="return confirm('Are you sure?')">
                <input name="session_id" value="<?=$serie_info['result']['session_id']?>" hidden>
                <input name="serie_id" value="<?=$serie_info['result']['serie_id']?>" hidden>
                <button>Delete Serie</button>
            </form>
        </tr>
    </td>
</table>


<form method="post" action="/?route=admin/selectHit">

    <?php foreach ($serie_info['result'] as $key => $value){
        if ($key == 'session_id' || $key == 'serie_id'){
            ?>
            <input name="<?=$key?>" value="<?=$value?>" hidden>
            <?php } else {
        echo $key.': '?><input type="text" name="<?=$key?>" value="<?=$value?>" readonly><br>
    <?php }}
    if (!$hit_list['result'] == array()){
        ?>
        hit_list: <select name="hit_id">
            <?php $i=1;
            foreach ($hit_list['result'] as $value){
                ?>
                <option value="<?=$value['hit_id']?>"><?=$i?></option>
                <?php $i++;
            }    ?>
        </select>
        <button>Watch the Hit</button>
        <?php
    } else {
        echo '<i>no hits in serie</i>';
    }
    ?>


</form>
<br>
<form method="post" action="/?route=admin/newHitForm">
    <input name="serie_id" value="<?=$serie_info['result']['serie_id']?>" hidden>
    <button type="button" onclick="history.back()">Back</button>
    <input name="session_id" value="<?=$_POST['session_id']?>" hidden>
    <button>Add new Hit</button>
</form>
</body>
</html>

