<html>
<head>
    <meta charset="UTF-8">
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="../../Js/scripts.js"></script>
</head>
<body>
<table>
    <td>
        <tr>
            <form method="post" action="/?route=admin/editHitForm">
                <?php foreach ($hit_info['result'] as $key => $value){
                    ?><input type="text" name="<?=$key?>" value="<?=$value?>" hidden>
                <?php }    ?>
                <button>Edit hit</button>
            </form>
        </tr>
        <tr>
            &nbsp &nbsp
        </tr>
        <tr>
            <form method="post" action="/?route=admin/deleteHit" onsubmit="return confirm('Are you sure?')">
                <input name="serie_id" value="<?=$hit_info['result']['serie_id']?>" hidden>
                <input name="hit_id" value="<?=$hit_info['result']['hit_id']?>" hidden>
                <button>Delete hit</button>
            </form>
        </tr>
    </td>
</table>

<form method="post" action="">

    <?php foreach ($hit_info['result'] as $key => $value){
    if ($key == 'hit_id' || $key == 'serie_id'){
        ?>
        <input name="<?=$key?>" value="<?=$value?>" hidden>
    <?php } else {
        echo $key.': '?><input type="text" name="<?=$key?>" value="<?=$value?>" readonly><br>
    <?php }}    ?>

    <button type="button" onclick="history.back()">Back</button>

</form>
</body>
</html>



