<html>
<head>
    <meta charset="UTF-8">
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="../../Js/scripts.js"></script>
</head>
<body>

<table>
    <td>
        <tr>
            <form method="post" action="/?route=admin/editSessionForm">
                <?php foreach ($session_info['result'] as $key => $value){
                    ?><input type="text" name="<?=$key?>" value="<?=$value?>" hidden>
                <?php }    ?>
                <button>Edit session</button>
            </form>
        </tr>
        <tr>
            &nbsp &nbsp
        </tr>
        <tr>
            <form method="post" action="/?route=admin/deleteSession" onsubmit="return confirm('Are you sure?')">
                <input name="session_id" value="<?=$session_info['result']['session_id']?>" hidden>
                <button>Delete Session</button>
            </form>
        </tr>
    </td>
</table>


<form method="post" action="/?route=admin/selectSerie">
    <?php foreach ($session_info['result'] as $key => $value){
        if ( $key != 'session_id' ){
        echo $key.': '?><input type="text" name="<?=$key?>" value="<?=$value?>" readonly><br>
    <?php } else{
        ?><input name="<?=$key?>" value="<?=$value?>" hidden><?php
    }}
    if (!$serie_list['result'] == array()){
        ?>
        serie_list: <select name="serie_number">
            <?php foreach ($serie_list['result'] as $value){?>
                <option value="<?=$value['number']?>"><?=$value['number'].' - '.$value['name']?></option>
            <?php }    ?>

        </select>
        <button>Watch the serie</button>
    <?php
    } else {
        echo '<i>no series in session</i>';
    }
    ?>
</form>
<br>
<br>


<form method="post" action="/?route=admin/newSerieForm">
    <input name="session_id" value="<?=$session_info['result']['session_id']?>" hidden>
    <button type="button" onclick="history.back()">Back</button>
    <button>Add new Serie</button>
</form>
</body>
</html>