
<form method="post" action="test.php">
    <?php foreach ($session_info as $key => $value){
        echo $key.': '?><input type="text" name="<?=$key?>" value="<?=$value?>" readonly><br>
    <?php }    ?>

    <select name="serie_number">
        <?php foreach ($series_info as $value){?>
            <option><?=$value['number']?></option>
        <?php }    ?>

    </select>


    <button>test</button>
</form>
