<h1>Contact Us</h1>

<p><span style="color: red"><?=Session::getFlash()?></span></p>
<form class="form-horizontal" method="post">
    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
        <div class="col-sm-4">
            <input type="email" class="form-control" name="email" value="<?=isset($email)?$email:''?>" id="inputEmail3" placeholder="Email">
        </div>
    </div>
    <div class="form-group">
        <label for="inputMessage" class="col-sm-2 control-label">Message</label>
        <div class="col-sm-4">
            <textarea class="form-control" name="message" id="inputMessage" placeholder="Enter your message"></textarea>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Send</button>
        </div>
    </div>
</form>