<div class="row" style="color: rgba(21, 31, 147, 0.84);">
    <div class="col-xs-12">
        <h1>
            Weclome to WEBER shooting gallery
        </h1>
        <br><br><br><br>
    </div>
    <div class="col-xs-6">
        <iframe width='100%' height="300px" src='https://www.youtube.com/embed/KihAwNn-zoM' frameborder='0' allowfullscreen></iframe>
    </div>
    <div class="col-xs-6">
        A hiedelemmel ellentétben a Lorem Ipsum nem véletlenszerû szöveg.
        Gyökerei egy Kr. E. 45-ös latin irodalmi klasszikushoz nyúlnak.
        Richarrd McClintock a virginiai Hampden-Sydney egyetem professzora kikereste
        az ismeretlenebb latin szavak közül az egyiket (consectetur) egy Lorem Ipsum részletbõl,
        és a klasszikus irodalmat átkutatva vitathatatlan forrást talált.
        A Lorem Ipsum az 1.10.32 és 1.10.33-as de Finibus Bonoruem et Malorum részleteibõl
        származik (A Jó és Rossz határai - Cicero), Kr. E. 45-bõl. A könyv az etika elméletét
        tanulmányozza, ami nagyon népszerû volt a reneszánsz korban. A Lorem Ipsum elsõ sora,
        Lorem ipsum dolor sit amet.. a 1.10.32-es bekezdésbõl származik.

        A Lorem Ipsum alaprészlete, amit az 1500-as évek óta használtak, az érdeklõdõk kedvéért
        lent újra megtekinthetõ. Az 1.10.32 és 1.10.33-as bekezdéseket szintén eredeti formájukban
        reprodukálták a hozzá tartozó angol változattal az 1914-es fordításból H. Rackhamtól.
    </div>
    <div class="col-xs-12">
            A hiedelemmel ellentétben a Lorem Ipsum nem véletlenszerû szöveg.
            Gyökerei egy Kr. E. 45-ös latin irodalmi klasszikushoz nyúlnak.
            Richarrd McClintock a virginiai Hampden-Sydney egyetem professzora kikereste
            az ismeretlenebb latin szavak közül az egyiket (consectetur) egy Lorem Ipsum részletbõl,
            és a klasszikus irodalmat átkutatva vitathatatlan forrást talált.
            A Lorem Ipsum az 1.10.32 és 1.10.33-as de Finibus Bonoruem et Malorum részleteibõl
            származik (A Jó és Rossz határai - Cicero), Kr. E. 45-bõl. A könyv az etika elméletét
            tanulmányozza, ami nagyon népszerû volt a reneszánsz korban. A Lorem Ipsum elsõ sora,
            Lorem ipsum dolor sit amet.. a 1.10.32-es bekezdésbõl származik.

            A Lorem Ipsum alaprészlete, amit az 1500-as évek óta használtak, az érdeklõdõk kedvéért
            lent újra megtekinthetõ. Az 1.10.32 és 1.10.33-as bekezdéseket szintén eredeti formájukban
            reprodukálták a hozzá tartozó angol változattal az 1914-es fordításból H. Rackhamtól.
            A hiedelemmel ellentétben a Lorem Ipsum nem véletlenszerû szöveg.
            Gyökerei egy Kr. E. 45-ös latin irodalmi klasszikushoz nyúlnak.
            Richarrd McClintock a virginiai Hampden-Sydney egyetem professzora kikereste
            az ismeretlenebb latin szavak közül az egyiket (consectetur) egy Lorem Ipsum részletbõl,
            és a klasszikus irodalmat átkutatva vitathatatlan forrást talált.
            A Lorem Ipsum az 1.10.32 és 1.10.33-as de Finibus Bonoruem et Malorum részleteibõl
            származik (A Jó és Rossz határai - Cicero), Kr. E. 45-bõl. A könyv az etika elméletét
            tanulmányozza, ami nagyon népszerû volt a reneszánsz korban. A Lorem Ipsum elsõ sora,
            Lorem ipsum dolor sit amet.. a 1.10.32-es bekezdésbõl származik.

            A Lorem Ipsum alaprészlete, amit az 1500-as évek óta használtak, az érdeklõdõk kedvéért
            lent újra megtekinthetõ. Az 1.10.32 és 1.10.33-as bekezdéseket szintén eredeti formájukban
            reprodukálták a hozzá tartozó angol változattal az 1914-es fordításból H. Rackhamtól.
    </div>
</div>