<h1>Login</h1>

<p><span style="color: red"><?=Session::getFlash()?></span></p>
<form class="form-horizontal" method="post">
    <div class="form-group">
        <label for="inputNickname" class="col-sm-2 control-label">Nickname</label>
        <div class="col-sm-3">
            <input type="text" class="form-control" name="nickname" value="<?=(isset($nickname)?$nickname:'')?>" id="inputNickname" placeholder="Enter your nick">
        </div>
    </div>
    <div class="form-group">
        <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
        <div class="col-sm-3">
            <input type="password" class="form-control" name="password" id="inputPassword3" placeholder="Password">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Sign in</button>
        </div>
    </div>
</form>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <br><p><a href="?route=security/registration">I need registration</a></p>


    </div>
</div>
