<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/gif" href="helpers/img/icon.png" />
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Weber</title>

    <!-- Bootstrap -->
<link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div class="container" role="navigation">
    <ul class="nav nav-tabs">
        <li role="presentation"><a href="/">Home</a></li>
        <li role="presentation"><a href="?route=index/about">About</a></li>
        <li role="presentation"><a href="?route=index/contact">Contact</a></li>
        <?php if (Session::has('user')): ?>
        <?php if (Session::get('user')['nickname'] == 'Admin'){
            ?><li role="presentation"><a href="?route=admin/index">Administration</a></li>
        <?php   } ?>
        <li role="presentation"><a href="?route=cabinet/index">My cabinet</a>
        <li role="presentation"><a href="?route=security/logout">Logout <?=(Session::get('user')['first_name'])?></a>
        <?php else: ?>
        <li role="presentation"><a href="?route=security/login">Login</a>
        <?php endif ?>
    </ul>
</div>
<br><br><br>
<div class="container">
    <?=$content?>
</div>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.min.js"></script>
</body>
</html>
